
SET IDENTITY_INSERT TIPO_SERVICIOS ON
GO

INSERT INTO TIPO_SERVICIOS (ID, NOMBRE) VALUES (1, 'Hotel');
INSERT INTO TIPO_SERVICIOS (ID, NOMBRE) VALUES (2, 'Habitacion');
INSERT INTO TIPO_SERVICIOS (ID, NOMBRE) VALUES (3, 'Paquete');

GO
SET IDENTITY_INSERT TIPO_SERVICIOS OFF
GO
SET IDENTITY_INSERT SERVICIOS ON
GO

INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (1, 'Piscina', 1);
INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (2, 'Restaurante', 1);
INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (3, 'Gimnasio', 1);
INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (4, 'WiFi', 2);
INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (5, 'Despertador', 2);
INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (6, 'Minibar', 2);
INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (7, 'Desayuno Gratis', 3);
INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (8, 'Mascota -50%', 3);
INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (9, 'Menores -50%', 3);

GO
SET IDENTITY_INSERT SERVICIOS OFF
GO