
INSERT INTO TIPO_SERVICIOS (ID, NOMBRE) VALUES (1, 'COMIDAS');
INSERT INTO TIPO_SERVICIOS (ID, NOMBRE) VALUES (2, 'HABITACIONES');

INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (1, 'DESAYUNO', 1);
INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (2, 'ALMUERZO', 1);
INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (3, 'CENA', 1);
INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (4, 'INDIVIDUAL', 2);
INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (5, 'INDIVIDUAL DOBLE', 2);
INSERT INTO SERVICIOS (ID, NOMBRE, TIPO_SERVICIO) VALUES (6, 'MATRIMONIAL', 2);

